#!/bin/bash
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/ssl-resource
cat > $payload <&0
dns=$(jq -r '.source.dns // ""' < $payload)

certificate_file=$(mktemp)
echo -n | openssl s_client -servername "$dns" -connect "$dns":443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $certificate_file

days_left=$($(dirname $0)/days_left.sh $dns $certificate_file)

ver=$( jq -n \
                --arg dl "$days_left" \
                '[{days_left: $dl}]' )

trap "unlink $certificate_file" EXIT
echo $ver >&3
